# D1 I1 C1
# D1 I2 C1 <- Default
# D1 I2 C2
# D1 I2 C3
# D1 I2 C4
# ---- 
# D2 I2 C1
output_file: {'origin': 'TUTO_task_Multi_Pitch_Estimation.ipynb', 'ext': '_D1-I2-C1.ipynb'}
dataset:
    # D1
    {'base': bach10, 'do_f0_annot': frame}
    # D2
    #{'base': maps, 'do_f0_annot': segment}
feature:
    # I1
    #{'type': hcqt, 'h_l': [1], 'bins_per_semitone': 5, 'n_octaves': 6, 'fmin': 32.7,  'hop_length': 512, 'patch_L_frame': 64, 'patch_STEP_frame': 32}
    # I2
    {'type': hcqt, 'h_l': [0.5, 1, 2, 3, 4, 5] ,'bins_per_semitone': 5, 'n_octaves': 6, 'fmin': 32.7,  'hop_length': 512, 'patch_L_frame': 64, 'patch_STEP_frame': 32}
model:
    name: Bittner
    block_l: # A list of blocks
    - sequential_l: # -- Each block is a list of sequential
        - layer_l: # --- Each sequential is a list of layer
            - [BatchNorm2d, {'num_features': -1}]
            - [Conv2d, {'in_channels': -1, 'out_channels': 128, 'kernel_size': [5,5], 'stride': 1, 'padding': 'same'}]
            - [Activation, ReLU]
        - layer_l:
            - [BatchNorm2d, {'num_features': -1}]
            # C1
            - [Conv2d, {'in_channels': -1, 'out_channels': 64, 'kernel_size': [5,5], 'stride': 1, 'padding': 'same'}]
            - [Activation, ReLU]
            # C2
            #- [Conv2dDS, {'in_channels': -1, 'out_channels': 64, 'kernel_size': [5,5], 'stride': 1, 'padding': 'same'}]
            #- [Activation, ReLU]
            # C3 / C4
            #- [Conv2dRes, {'in_channels': -1, 'out_channels': 64, 'kernel_size': [5,5], 'stride': 1, 'padding': 'same'}]
        - layer_l:
            - [BatchNorm2d, {'num_features': -1}]
            # C1
            - [Conv2d, {'in_channels': -1, 'out_channels': 64, 'kernel_size': [3,3], 'stride': 1, 'padding': 'same'}]
            - [Activation, ReLU]
            # C2
            #- [Conv2dDS, {'in_channels': -1, 'out_channels': 64, 'kernel_size': [3,3], 'stride': 1, 'padding': 'same'}]
            #- [Activation, ReLU]
            # C3
            #- [Conv2dRes, {'in_channels': -1, 'out_channels': 64, 'kernel_size': [5,5], 'stride': 1, 'padding': 'same'}]
            # C4
            #- [Conv2dNext, {'in_channels': -1, 'out_channels': 64, 'stride': 1, 'padding': 'same'}]
        - layer_l:
            - [BatchNorm2d, {'num_features': -1}]
            # C1
            - [Conv2d, {'in_channels': -1, 'out_channels': 64, 'kernel_size': [3,3], 'stride': 1, 'padding': 'same'}]
            - [Activation, ReLU]
            # C2
            #- [Conv2dDS, {'in_channels': -1, 'out_channels': 64, 'kernel_size': [3,3], 'stride': 1, 'padding': 'same'}]
            #- [Activation, ReLU]
            # C3
            #- [Conv2dRes, {'in_channels': -1, 'out_channels': 64, 'kernel_size': [5,5], 'stride': 1, 'padding': 'same'}]
            # C4
            #- [Conv2dNext, {'in_channels': -1, 'out_channels': 64, 'stride': 1, 'padding': 'same'}]
        - layer_l:
            - [BatchNorm2d, {'num_features': -1}]
            # --- C1
            - [Conv2d, {'in_channels': -1, 'out_channels': 8, 'kernel_size': [70,3], 'stride': 1, 'padding': 'same'}]
            - [Activation, ReLU]
        - layer_l:
            - [BatchNorm2d, {'num_features': -1}]
            - [Conv2d, {'in_channels': -1, 'out_channels': 1, 'kernel_size': [1,1], 'stride': 1, 'padding': 'same'}]

